source 'https://rubygems.org'
ruby "2.0.0"

gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'rest-client'
gem 'fog'
gem 'aws-sdk'
gem 'carrierwave'
gem 'carrierwave-datamapper'
gem 'mini_magick'
gem 'meme_captain'
gem 'will_paginate'
gem 'dotenv'
gem 'carrierwave-processing'
gem 'newrelic_rpm'